name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2.1.4
        with:
          python-version: '3.7'

      - name: Run a multi-line script
        shell: python
        run: |
          import os
          import sys
          print(sys.version)
          from pathlib import Path
          os.environ['GITHUB_ENV'] = 'ANSWER=A42'

      - name: Create Awesome Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 7b35716db8bedb6914c6cf2fab3a4dd0
          filename: test.json
          label: Hello
          message: ${{ env.ANSWER }}
          color: orange
