name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2.1.4
        with:
          python-version: '3.7'

      - name: Run unit tests script
        shell: python
        run: |
          import sys
          sys.path.append('./.github/workflows')
          from tests_utils import run_tests

          passed, total = run_tests()
          failed = total - passed

          if passed != total:
            raise Exception(f"{failed}/{total} tests failed!")
