name: lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2.1.4
        with:
          python-version: '3.7'

      - name: Run a multi-line script
        shell: python
        run: |
          import os; import sys; print(sys.version)
          from pathlib import Path
          sys.path.append('./.github/workflows')
          from lint_crn import lint_crn, find_crn
          from lint_dna import lint_dna, find_dna
          
          crn_fpath = find_crn()
          lint_crn(crn_fpath)
          
          dna_fpath = find_dna()
          lint_dna(dna_fpath)
